title: Heng Ma
description: >-
  Researcher & Engineer. Exploring AI, systems, and everything in between.
baseurl: ""
url: "https://hengma1001.github.io"

# Build settings
theme: minima
markdown: kramdown

# Use underscores in post URLs: /blog/2026-08-12-welcome.html
permalink: /blog/:year-:month-:day-:title.html

# Minima theme settings
minima:
  skin: dark

# Navigation
nav_pages:
  - publications.md
  - blog/index.html
  - about.md

# Author
author: Heng Ma

# Social
github_username: hengma1001

# Exclude from processing
exclude:
  - .git
  - .github
  - Gemfile*
  - node_modules
  - vendor
